// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibraryPlaces.Models;

public partial class Category
{
    public int Id { get; set; }

    public string Title { get; set; }

    public virtual ICollection<Place> Places { get; set; } = new List<Place>();
}