// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibraryPlaces.Models;

public partial class Place
{
    public int Id { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitute { get; set; }

    public string ImageUrl { get; set; }

    public string Description { get; set; }

    public string Title { get; set; }

    public int IdCategory { get; set; }

    public virtual Category IdCategoryNavigation { get; set; }
}